name: Node.js Build and Test

on:
  push:
    branches:
      - main  # Is branch pe push hone par workflow chalega
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to project directory
        run: cd gym-fit  # Yahan apne project ka correct folder ka naam dena

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
